# Some hooks taken from https://github.com/pytest-dev/pytest/blob/master/.pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.5.0
  hooks:
  - id: reorder-python-imports
- repo: local
  hooks:
  - id: tests
    name: pytest
    entry: pytest -vv
    pass_filenames: false
    language: system
    types: [python]
    stages: [push]
