# Some hooks taken from https://github.com/pytest-dev/pytest/blob/master/.pre-commit-config.yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        exclude: ^tests/.*
        additional_dependencies:
          - "pydantic"
        args: [
            --ignore-missing-imports, # optional: this argument ignores errors about imports that cannot be resolved
            --disallow-untyped-defs, # optional: this argument disallows defining functions without type annotations
          ]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-docstrings==1.7.0
  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: local
    hooks:
      - id: tests
        name: pytest
        entry: python -m pytest -vv
        pass_filenames: false
        language: system
        types: [python]
        stages: [push]
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.0.1
    hooks:
      - id: doctoc
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.1.3
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        description: "Checks the style of Markdown/CommonMark files."
        entry: markdownlint-cli2
        language: node
        types: [markdown]
        minimum_pre_commit_version: 0.15.0
