version: "3.8"
services:
  deposit-function:
    build: .
    environment:
      - COINBASE_API_BASE_URL=http://mock-server:3001
      - COINBASE_TRADING_API_KEY=${COINBASE_TRADING_API_KEY}
      - COINBASE_TRADING_PRIVATE_KEY=${COINBASE_TRADING_PRIVATE_KEY}
      - LOGGING_LEVEL=DEBUG
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/func
    container_name: deposit-function
    command:
      [
        "functions-framework",
        "--target=coinbase_deposit",
        "--signature-type=event",
        "--debug",
      ]
    ports:
      - "8081:8080"
    depends_on:
      - mock-server

  orders-function:
    build: .
    environment:
      - COINBASE_API_BASE_URL=http://mock-server:3001
      - COINBASE_TRADING_API_KEY=${COINBASE_TRADING_API_KEY}
      - COINBASE_TRADING_PRIVATE_KEY=${COINBASE_TRADING_PRIVATE_KEY}
      - LOGGING_LEVEL=DEBUG
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/func
    container_name: orders-function
    command:
      [
        "functions-framework",
        "--target=coinbase_orders",
        "--signature-type=event",
        "--debug",
      ]
    ports:
      - "8082:8080"
    depends_on:
      - mock-server

  mock-server:
    image: mockoon/cli:6.1.0
    command: ["--data", "data", "--port", "3001"]
    volumes:
      - ./mock_servers/coinbase/environment.json:/data:readonly
    ports:
      - "3001:3000"
